### ISSUE TITLE
Creation of steam folder outside relative foswink

### ISSUE THREAD

**Issue by ghost** [OpulentXYZ/foswink#4]
Steamcmd creates a dir outside foswink and I believe it isn't important so it should be put into the folder and renamed possibly cacbe?

**Comment by Djlavoy** [comment]
Fixed in commit https://github.com/OpulentXYZ/foswink/commit/e6c5935ce1f62d189c3051d7ae96952438461431
It seems this Directory was created for SteamCMD to have a place for log files I created a function to remove the directory after its been use to keep things clean, But I don’t see any harm in having it there
